package com.tms.mcq.framework.exception;

public enum ErrorType {
    ILLEGAL_ARGUMENT,MISSING_VALUE,NOT_EXIST,ALREADY_EXIST,TIME_OUT,NOT_RESPONDING,SERVER_ERROR,INVALID_ACTION,UNATHORIZE_OPERATION,
    OPERATION_NOT_SUPPORTED,INVALID_STATE,IO_EXCEPTION;
}
